### ISSUE TITLE
Resource requirement for building the index for 100 human haplotypes

### ISSUE THREAD

**Issue by lh3** [mohsenzakeri/Movi#14]
I could build a movi index for a collection of bacterial genomes. When I tried to build a movi index for [100 human haplotypes](https://zenodo.org/records/10703141), the `newscanNT.x` step in bigbwt finished in ~16 hours. However, the following pfp-thresholds step failed. I didn't see an error message but it seemed to be caused by insufficient memory as our machine only has ~300GB available. How much memory would pfp-thresholds require for 100 human haplotypes? How long will BWT construction take? Thanks!

**Comment by mohsenzakeri** [comment]
Hi @lh3, 

For 100 human genomes, the 16-hours runtime for `newscaNT.x` is reasonable, and the interruption you observed is probably due to insufficient memory, as you mentioned. 

Based on my experience, you would need about 800 GB for running pfp-thresholds on 94 human genomes (specifically HPRC genomes), and it will take about 30 hours. 

Best,
Mohsen

**Comment by mohsenzakeri** [comment]
Thank you for the tip. I will definitely look into it. As you mentioned, we need to run pfp-thresholds for the thresholds data structure that it produces along with the BWT. However, we are also developing a variation of Movi that does not require thresholds, so "grlBWT" could be useful for us. Thank you!

**Comment by lh3** [comment]
A followup: I ran pfp-thresholds on a slower machine with 1TB RAM. It finished in 51 hours in 790GB RAM. Nonetheless, movi index failed due to "std::bad_alloc". How much memory would movi index need?

**Comment by mohsenzakeri** [comment]
For the HPRC dataset it needs 1.1 TB RAM, so that was probably why your run failed.  We are now working on improvements for decreasing the memory usage during build, but until then I can build and share the Movi index with you if you could please point me to the exact set of haplotypes that you want to have in the index.

**Comment by lh3** [comment]
Thanks for the offer. I am using genomes starting with "1" or "4" in this agc file:

https://zenodo.org/records/10703141/files/human100p10.agc?download=1

There are exactly 100 of them. Ignore the rest of the assemblies in the agc file for now. By the end of this year, we may have ~400 human haplotypes.

I am looking at Movi as I have been working on [ropebwt3](https://github.com/lh3/ropebwt3) and wonder how far it is from the state of art.

**Comment by mohsenzakeri** [comment]
Thank you for sharing the details. I started building the index. I will update you once the index is built. Here is the list of the sequences I am building the index on: [100.list.txt](https://github.com/user-attachments/files/15876125/100.list.txt)

I will update you once the index is built.

**Comment by mohsenzakeri** [comment]
Hi again,

Here is the [link ](https://livejohnshopkins-my.sharepoint.com/:f:/g/personal/mzakeri1_jh_edu/ElihOV97JYtJsqO03JOu-1EBDSZwqEo8loooOYDYCdKGcw) to download the Movi index built on the 100 human haplotypes.

Please note that you should provide the path of the **directory containing** the index file (`movi_index.bin`) to the `query` command.

Also, if you are using the tagged version of the Movi (1.0), the command is:
`movi-default query <index_dir> <reads_file>`
If you use the latest version of the code at the main branch, the command is:
`movi-default query --index <index_dir> --read <reads_file>`

Note that the prefetching strategy (which is 2~3 times faster and explained [here](https://www.biorxiv.org/content/10.1101/2023.11.04.565615v2)) is only implemented in the latest version of the main branch.

**Comment by lh3** [comment]
Thank you so much for this. I have just downloaded the file and will play with it.

**Comment by lh3** [comment]
I used movi to find the PML of 1 million HG002 short reads. This took 26.5 seconds, excluding the index loading time:
```txt
Time measured for processing the reads: 26.497 seconds.
```
Ropebwt3 took 119.1 seconds on a single thread to report "greedy MEMs" (furthest backward extension followed by furthest forward extension; then repeat) and 190.7 seconds to report SMEMs.

**Comment by mohsenzakeri** [comment]
That sounds great. Thank you for sharing the results. Let me know if you need help with anything else.

**Comment by mohsenzakeri** [comment]
Hi again @lh3 ,
I wanted to mention that the index I built and shared above includes both the forward and reverse complement of all the genomes. That is, the BWT is built over the fw+rc fasta. We do that to avoid querying the reads twice. So, I wanted to make sure if that was something that you also want? If not, I can build a new version of the index that only includes the forward strand.
Best,
Mohsen

**Comment by lh3** [comment]
BWA, fermi and ropebwt all use BWT including both strands. This enables forward-backward search with a single BWT and as you say, it simplifies and speeds up DNA string matching.
