### ISSUE TITLE
Movi build fails

### ISSUE THREAD

**Issue by marade** [mohsenzakeri/Movi#6]
...
[ 70%] Built target sdsl
[ 80%] Building CXX object CMakeFiles/movi-default.dir/src/movi.cpp.o
[ 80%] Building CXX object CMakeFiles/movi-default.dir/src/move_structure.cpp.o
/home/ubuntu/Movi/src/move_structure.cpp: In member function ‘void MoveStructure::build_rlbwt(char*)
 :
/home/ubuntu/Movi/src/move_structure.cpp:429:20: error: ‘streampos’ is not a member of ‘std::ios_base’
  429 |     std::ios_base::streampos end_pos = bwt_file.tellg();
      |                    ^~~~~~~~~
/home/ubuntu/Movi/src/move_structure.cpp:430:33: error: ‘end_pos’ was not declared in this scope
  430 |     std::cerr << "end_pos: " << end_pos << "\n";
      |                                 ^~~~~~~
/home/ubuntu/Movi/src/move_structure.cpp: In member function ‘void MoveStructure::build(std::ifstream&)’:
/home/ubuntu/Movi/src/move_structure.cpp:467:20: error: ‘streampos’ is not a member of ‘std::ios_base’
  467 |     std::ios_base::streampos end_pos = bwt_file.tellg();
      |                    ^~~~~~~~~
/home/ubuntu/Movi/src/move_structure.cpp:468:33: error: ‘end_pos’ was not declared in this scope
  468 |     std::cerr << "end_pos: " << end_pos << "\n";
      |                                 ^~~~~~~
gmake[2]: *** [CMakeFiles/movi-default.dir/build.make:90: CMakeFiles/movi-default.dir/src/move_structure.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:495: CMakeFiles/movi-default.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2

**Comment by mohsenzakeri** [comment]
Hi @marade,

Thank you for sharing the error message you observed.  I believe this is due to using a method (`std::ios_base::streampos`) in the code that is deprecated in C++17. I should have specified in the cmake file to use an older C++ compiler (e.g., C++14). I have added this fix now, please try again and let me know if you are able to successfully build `Movi`.

Best,
Mohsen
